{% set name = "AutoDock-GPU" %}
{% set version = "1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ccsb-scripps/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dcb5f4f59d6237ee4735370fbf636dae76e3511e254d34c9f38694d17399addb
  patches:
    - makefile.cuda.patch

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cuda_driver
  host:
    - cudatoolkit
  run:
    - cudatoolkit

test:
  commands:
    - test -f ${PREFIX}/bin/autodock_gpu_32wi
    - test -f ${PREFIX}/bin/autodock_gpu_64wi
    - test -f ${PREFIX}/bin/autodock_gpu_128wi
    - test -f ${PREFIX}/bin/autodock_gpu_256wi

about:
  home: https://github.com/ccsb-scripps/AutoDock-GPU
  dev_url: https://github.com/ccsb-scripps/AutoDock-GPU
  doc_url: https://github.com/ccsb-scripps/AutoDock-GPU/wiki/
  license: GPL-2.0 AND LGPL-2.1-or-later
  license_file:
    - LICENSE
    - LICENSE_LGPL
  summary: "AutoDock for GPUs using OpenCL."
