{% set name = "metabolic" %}
{% set version = "20210303" %}
{% set sha256 = "9b664da9f00a4af96d89d39bd25ac744c14e37f8b45b886903a0188defd34a72" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/AnantharamanLab/METABOLIC/archive/8fdc70d2b714f17b9f77aff0bc6b2b79d5005262.zip
    sha256: {{ sha256 }}
    patches:
      - perl_path.patch

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - r-base 3.6*
    - hmmer >3.1
    - diamond
  run:
    - hmmer >3.1
    - prodigal >=2.6.3
    - sambamba >=0.7.0
    - bamtools >=2.4.0
    - coverm
    - gtdbtk
    - diamond
    - bowtie2
    - tbb <=2020.2
    - r-base 3.6*
    - r-tidyverse 1.3.0
    - r-diagram
    - r-ggthemes
    - r-ggalluvial
    - r-ggraph
    - r-openxlsx
    - r-pdftools
    - perl 5.26
    - perl-data-dumper
    - perl-excel-writer-xlsx
    - perl-posix
    - perl-getopt-long
    - perl-statistics-descriptive
    - perl-bioperl 1.7
    - perl-array-split
    - perl-parallel-forkmanager
    - perl-sub-exporter-simple
    - perl-file-spec
    - gdown

test:
  commands:
    - METABOLIC-C.pl  --help
    - METABOLIC-G.pl --help

about:
  home: https://github.com/AnantharamanLab/METABOLIC
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: "A scalable high-throughput metabolic and biogeochemical functional trait profiler."
  dev_url: https://github.com/AnantharamanLab/METABOLIC
