variables:
  HCC_BIOCONDA_UTILS_TAG: "gitlabci-master"
  BIOCONDA_UTILS_BUILD_ARGS: "--loglevel=info --keep-old-work"
  BIOCONDA_UTILS_LINT_ARGS: "--loglevel=info"
  MINICONDA_VER: "4.6.14"
  SUBDAGS: "1"
  SUBDAG: "0"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

stages:
  - build
  - deploy
  - sync-to-github

build-linux:
  stage: build
  image: quay.io/bioconda/bioconda-utils-build-env-cos7:latest
  except:
    - master
  tags:
    - docker
  before_script:
    - export ANACONDA_PREFIX=/opt/conda
    - export HOME=/home/conda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/conda_build_src
      - .cache/conda_pkgs

.build-osx:
  stage: build
  except:
    - master
  tags:
    - osx
  before_script:
    - git fetch origin +master:master
    - export ANACONDA_PREFIX=`mktemp -d`/anaconda
    - export CONDARC=$ANACONDA_PREFIX/.condarc && rm -rf ~/.condarc
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
    - rm -rf $ANACONDA_PREFIX

deploy-linux:
  stage: deploy
  image: quay.io/bioconda/bioconda-utils-build-env-cos7:latest
  only:
    - master
  tags:
    - docker
  before_script:
    - export ANACONDA_PREFIX=/opt/conda
    - export HOME=/home/conda
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/conda_build_src
      - .cache/conda_pkgs
    policy: pull

.deploy-osx:
  stage: deploy
  only:
    - master
  tags:
    - osx
  before_script:
    - git fetch origin +master:master
    - export ANACONDA_PREFIX=`mktemp -d`/anaconda
    - export CONDARC=$ANACONDA_PREFIX/.condarc && rm -rf ~/.condarc
    - scripts/gitlabci-setup.sh
  script:
    - scripts/gitlabci-run.sh
    - rm -rf $ANACONDA_PREFIX

sync-to-github:
  stage: sync-to-github
  image: unlhcc/crane-build-el6
  allow_failure: yes
  only:
    - master
  tags:
    - docker
  script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$GITHUB_SSH_DEPLOY_PKEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git checkout master
    - git remote add github git@github.com:unlhcc/hcc-conda-recipes.git
    - git push github +master
