{% set name = "Cenote-Taker2" %}
{% set version = "2.1.2" %}
{% set sha256 = "51f73d561bc692bf2e4cf71db75e9ba05da08fb9a41a7fb56548825d485e88c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mtisza1/Cenote-Taker2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - paths.patch

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python=3.6
    - prodigal=2.6.3
    - bwa=0.7.17
    - samtools=1.3
    - mummer=3.23
    - circlator=1.5.5
    - blast=2.9.0
    - bioawk=1.0
    - entrez-direct=13.3
    - krona=2.7.1
    - hmmer=3.3
    - bowtie2=2.3.5
    - trnascan-se=2.0.5
    - bbmap=37.62
    - tbl2asn-forever=25.7.1f
    - emboss=6.6.0
    - numpy=1.18.1
    - pandas=1.0.0
    - matplotlib-base=3.1.3
    - hhsuite=3.2.0
    - last=1047
    - phanotate
    - perl
    - coreutils
    - pysam=0.15.3
    - bedtools

test:
  commands:
    - run_cenote-taker2.py -h

about:
  home: https://github.com/mtisza1/Cenote-Taker2
  license: MIT
  license_family: MIT
  license_file: 
    - LICENSE
    - anicalc/LICENSE.txt
  summary: "Cenote-Taker2 is a pipeline for divergent virus discovery and annotation."
  dev_url: https://github.com/mtisza1/Cenote-Taker2
