package:
  name: mesa-libglw-cos7-x86_64
  version: 8.0.0

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/mesa-libGLw-8.0.0-5.el7.x86_64.rpm
    sha256: 24b1126d27ccd8798bb9775f495373d3a69cda6685508c05d471a29ba604a3b4
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/mesa-libGLw-8.0.0-5.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - rsync
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: mesa-license
  summary: (CDT) Xt / Motif OpenGL widgets
  description: |
    Mesa libGLw runtime library.

extra:
  skip-lints:
    - build_number_needs_reset
