c_compiler_version:
  - 7.5.* # [linux]
cxx_compiler_version:
  - 7.5.* # [linux]
fortran_compiler_version:
  - 7.5.* # [linux]
libpng:
  - 1.6*
glib:
  - 2.56*
jpeg:
  - 9*
freetype:
  - 2.9.1*
expat:
  - 2.2*
gsl:
  - 2.4*
r_base:
  - 3.5*
