{% set name = "afni" %}
{% set version = "18.2.06" %}
{% set sha256 = "dee033d8435740e844308415f73ce674c60f53ed42a52085bd706b05f2218042" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://github.com/{{ name }}/{{ name }}/archive/AFNI_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - makefile.patch
    - suma_makefile.patch
    - dcm2niix.patch

build:
  number: 3
  skip: True # [osx]
#  skip: True # [py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf
    - make
    - {{ cdt('mesa-libegl-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libglw-devel') }}
    - python 2.7*

  host:
    - python 2.7*
    - libpng
    - glib
    - jpeg
    - zlib
    - openssl
    - openmp
    - freetype
#    - mesa
    - libglu
    - xorg-libx11
    - xorg-libxt
    - xorg-libxext
    - xorg-libxi
    - xorg-libxft
    - xorg-libxcb
    - xorg-libxpm
    - expat
    - gsl
    - openmotif
    - openmotif-dev
    - netpbm
    - r-base
    - tcsh

  run:
    - python 2.7*
    - libpng
    - glib
    - jpeg
    - zlib
    - openssl
    - openmp
    - freetype
#    - mesa
    - libglu
    - xorg-libx11
    - xorg-libxt
    - xorg-libxext
    - xorg-libxi
    - xorg-libxft
    - xorg-libxcb
    - xorg-libxpm
    - expat
    - gsl
    - openmotif
    - netpbm
    - r-base
    - r-rmpi
    - r-afex
    - r-phia
    - r-snow
    - r-nlme
    - r-lme4
    - r-paran
    - r-psych
    - r-brms

test:
  commands:
    - afni --help
    - 3dRSFC -help

about:
  home: https://afni.nimh.nih.gov/afni
  summary: "AFNI is a suite of programs for looking at and analyzing 3D brain images."
  license: GPL-2.0
  license_family: GPL
  license_file: doc/README/README.copyright
  dev_url: https://github.com/afni/afni

extra:
  container:
    extended-base: True
